DROP TABLE IF EXISTS snowboarders;
DROP TABLE IF EXISTS messages;

CREATE TABLE snowboarders (
  id VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  name VARCHAR NOT NULL,
  age INT NOT NULL,
  profile VARCHAR NOT NULL
);