DROP TABLE IF EXISTS snowboarders;
DROP TABLE IF EXISTS events;

CREATE TABLE snowboarders (
  id VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  name VARCHAR NOT NULL,
  age INT NOT NULL,
  profile VARCHAR NOT NULL
);

CREATE TABLE events (
  id VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
  name VARCHAR NOT NULL,
  location VARCHAR NOT NULL,
  prize_money INT NOT NULL DEFAULT 0
);